project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - results.qmd
    - grazing.qmd
    - asv-analysis.qmd
    - sequence-qc.qmd

website:
  title: "Mid-Cayman Rise analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: results.qmd
        text: Summary of results
      - href: grazing.qmd
        text: Grazing analysis
      - href: asv-analysis.qmd
        text: Sequence analysis
      - href: sequence-qc.qmd
        text: Sequence QC & import

format:
  html:
    theme: minty
    css: styles.css
    code-fold: true
    toc: true
    toc-location: left
    number-sections: true
    number-depth: 2



